services:
  products-db:
    image: postgres:15
    container_name: products-db
    restart: always
    environment:
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_pass
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - products_data:/var/lib/postgresql/data

volumes:
  products_data:
